Llvdl\TweeterCoreBundle\Entity\Tweeter:
    type: entity
    table: tweeter
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 128
            unique: true