parameters:
    llvdl_tweeter_core.tweeter_service.class: Llvdl\TweeterCoreBundle\Service\TweetService
    llvdl_tweeter_core.tweet_repository.class: Llvdl\TweeterCoreBundle\Repository\Impl\TweetRepositoryDoctrineImpl
    llvdl_tweeter_core.tweeter_repository.class: Llvdl\TweeterCoreBundle\Repository\Impl\TweeterRepositoryDoctrineImpl

services:
    llvdl_tweeter_core.tweeter_repository:
        class: %llvdl_tweeter_core.tweeter_repository.class%
        arguments: [@doctrine.orm.entity_manager]
        public: false
    llvdl_tweeter_core.tweet_repository:
        class: %llvdl_tweeter_core.tweet_repository.class%
        arguments: [@doctrine.orm.entity_manager]
        public: false

    llvdl_tweeter_core.tweet_service:
        class: %llvdl_tweeter_core.tweeter_service.class%
        arguments: [@llvdl_tweeter_core.tweet_repository, @llvdl_tweeter_core.tweeter_repository]

